DROP TABLE users;
DROP TABLE films;
DROP TABLE film_likes;
DROP TABLE user_friends;
DROP TABLE film_genres;

CREATE TABLE IF NOT EXISTS users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    login VARCHAR,
    name VARCHAR,
    email VARCHAR,
    birthday DATE
);

CREATE TABLE IF NOT EXISTS films (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR,
    description VARCHAR,
    release_date DATE,
    duration INTEGER,
    --rate INTEGER,
    mpa_rating_id INTEGER
);

    CREATE TABLE IF NOT EXISTS film_likes (
    film_id INTEGER,
    user_id INTEGER
);

    CREATE TABLE IF NOT EXISTS user_friends (
    user_id INTEGER,
    friend_id INTEGER
);

    CREATE TABLE IF NOT EXISTS genres (
    id INTEGER PRIMARY KEY,
    genre_name VARCHAR
);

    MERGE INTO genres (id, genre_name)
    VALUES (1, 'Комедия'), (2, 'Драма'), (3, 'Мультфильм'), (4, 'Триллер'), (5, 'Документальный'), (6, 'Боевик')
    --ON CONFLICT (id) DO NOTHING
;

CREATE TABLE IF NOT EXISTS film_mpa_ratings (
    id INTEGER PRIMARY KEY,
    rating_name VARCHAR
);

    MERGE INTO film_mpa_ratings (id, rating_name)
    VALUES (1, 'G'), (2, 'PG'), (3, 'PG-13'), (4, 'R'), (5, 'NC-17')
    --ON CONFLICT (id) DO NOTHING
;

CREATE TABLE IF NOT EXISTS film_genres (
    film_id INTEGER,
    genre_id INTEGER
);